// Publish-and-pin: package the generated cpp + python targets as VERSIONED,
// checksummed, self-describing artifacts so the native C++ extractors and
// specklepy build against one pinned spec version — replacing today's sibling
// checkout (../speckle-bundle-spec/generated/cpp) and hand re-vendor.
//
// Operates on the already-committed generated/ files (guarded by `npm run check`),
// so it never touches the codegen→generated invariant. Pure Node, no duckdb.
// Deterministic: same spec + same generated/ → byte-identical lockfile (no
// wall-clock stamp), so the pin is reproducible and diffable.
//
//   node codegen/publish.mjs            # → dist/
//
// Produces:
//   dist/bundle-spec.lock.json               canonical pin manifest (version, specHash, per-file sha256)
//   dist/cpp/generated/cpp/*.h               headers + synthesized bundle_spec_version.h
//   dist/bundle-spec-cpp-<version>.tar.gz     fetchable C++ artifact (BUNDLE_SPEC points here)
//   dist/python/…                            installable `speckle-bundle-spec` package (+ _version.py)
//   (lock only) queryConformance             per-file pins of conformance/query/ for engines that vendor it

import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  copyFileSync,
  readdirSync
} from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(REPO, 'dist')

const sha256 = (buf) => 'sha256:' + createHash('sha256').update(buf).digest('hex')
const sha256File = (p) => sha256(readFileSync(p))
const rel = (p) => p.slice(REPO.length + 1)

// ── inputs ──
const pkg = JSON.parse(readFileSync(join(REPO, 'package.json'), 'utf8'))
const VERSION = pkg.version
// specHash = fingerprint of THE source of truth. The finest pin: two builds with
// the same specHash are provably the same format down to catalog rows/comments.
const SPEC_HASH = sha256File(join(REPO, 'spec', 'bundle-spec.sql'))
// schema_version is already stamped in the generated Python target — read it back
// (authoritative, avoids re-running duckdb here).
const SCHEMA_VERSION = Number(
  readFileSync(join(REPO, 'generated', 'python', 'bundle_spec.py'), 'utf8').match(
    /^SCHEMA_VERSION\s*=\s*(\d+)/m
  )?.[1]
)
if (!Number.isInteger(SCHEMA_VERSION))
  throw new Error('could not read SCHEMA_VERSION from generated/python/bundle_spec.py')

console.log(`bundle-spec publish  version=${VERSION}  schema_version=${SCHEMA_VERSION}`)
console.log(`  spec hash  ${SPEC_HASH}`)

// clean dist
rmSync(DIST, { recursive: true, force: true })
mkdirSync(DIST, { recursive: true })

// ── cpp target ──
const cppSrcDir = join(REPO, 'generated', 'cpp')
const cppOutDir = join(DIST, 'cpp', 'generated', 'cpp') // mirror repo layout → BUNDLE_SPEC works unchanged
mkdirSync(cppOutDir, { recursive: true })
const cppFiles = readdirSync(cppSrcDir).filter((f) => f.endsWith('.h'))
for (const f of cppFiles) copyFileSync(join(cppSrcDir, f), join(cppOutDir, f))

// synthesized pin header — makes the C++ artifact self-describing (assertable at build time)
const cppVersionHeader = `// GENERATED by codegen/publish.mjs — pin header for the published bundle-spec artifact.
// Lets a consumer assert exactly which spec version + fingerprint it built against.
#pragma once
#include <cstdint>
namespace bundlespec {
inline constexpr const char* kSpecVersion         = "${VERSION}";
inline constexpr const char* kSpecHash            = "${SPEC_HASH}";
inline constexpr int         kSchemaVersionPinned = ${SCHEMA_VERSION};
}  // namespace bundlespec
`
writeFileSync(join(cppOutDir, 'bundle_spec_version.h'), cppVersionHeader)

// ── python target: an installable package `speckle-bundle-spec` ──
const pySrcDir = join(REPO, 'generated', 'python')
const pyPkgDir = join(DIST, 'python', 'speckle_bundle_spec')
mkdirSync(pyPkgDir, { recursive: true })
const pyFiles = readdirSync(pySrcDir).filter((f) => f.endsWith('.py'))
for (const f of pyFiles) copyFileSync(join(pySrcDir, f), join(pyPkgDir, f))

writeFileSync(
  join(pyPkgDir, '_version.py'),
  `# GENERATED by codegen/publish.mjs — pin metadata for the published bundle-spec artifact.
SPEC_VERSION = "${VERSION}"
SPEC_HASH = "${SPEC_HASH}"
SCHEMA_VERSION = ${SCHEMA_VERSION}
`
)
writeFileSync(
  join(pyPkgDir, '__init__.py'),
  `"""Speckle bundle spec — pinned Python target (schema_version ${SCHEMA_VERSION})."""
from ._version import SPEC_VERSION, SPEC_HASH, SCHEMA_VERSION
from .bundle_spec import *  # noqa: F401,F403
from . import bundle_schemas  # noqa: F401
`
)
writeFileSync(
  join(DIST, 'python', 'pyproject.toml'),
  `# GENERATED by codegen/publish.mjs — installable pinned bundle-spec Python target.
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "speckle-bundle-spec"
version = "${VERSION}"
description = "Generated Python target of the Speckle bundle format spec (pinned)."
requires-python = ">=3.9"
license = { text = "Apache-2.0" }

[tool.setuptools]
packages = ["speckle_bundle_spec"]
`
)

// ── canonical lockfile: the single pin both consumers assert against.
//    Pins the GENERATED SOURCE content (what consumers vendor / include), NOT the
//    publish-synthesized packaging wrappers (bundle_spec_version.h, _version.py,
//    __init__.py, pyproject) — those are derived from the top-level version/specHash.
//    Keys mirror each consumer's natural layout: cpp under generated/cpp/ (the
//    BUNDLE_SPEC include root), python flat by basename (the vendored files). ──
const hashTree = (dir, ext, keyPrefix) =>
  Object.fromEntries(
    readdirSync(dir)
      .filter((f) => f.endsWith(ext))
      .sort()
      .map((f) => [keyPrefix + f, sha256File(join(dir, f))])
  )
// Recursive variant for the query conformance suite (bundle/, local/, json, harness) —
// keys are relative to conformance/query, matching a consumer's vendored layout.
const hashDeep = (dir, prefix = '') =>
  Object.fromEntries(
    readdirSync(dir, { withFileTypes: true })
      .sort((a, b) => a.name.localeCompare(b.name))
      .flatMap((e) =>
        e.isDirectory()
          ? Object.entries(hashDeep(join(dir, e.name), prefix + e.name + '/'))
          : [[prefix + e.name, sha256File(join(dir, e.name))]]
      )
  )

const lock = {
  name: pkg.name,
  version: VERSION,
  schemaVersion: SCHEMA_VERSION,
  specHash: SPEC_HASH,
  targets: {
    cpp: { include: 'generated/cpp', files: hashTree(cppSrcDir, '.h', 'generated/cpp/') },
    python: { package: 'speckle_bundle_spec', files: hashTree(pySrcDir, '.py', '') },
    queryConformance: {
      dir: 'conformance/query',
      files: hashDeep(join(REPO, 'conformance', 'query'))
    }
  }
}
const lockJson = JSON.stringify(lock, null, 2) + '\n'
writeFileSync(join(DIST, 'bundle-spec.lock.json'), lockJson)
copyFileSync(join(DIST, 'bundle-spec.lock.json'), join(DIST, 'cpp', 'bundle-spec.lock.json'))

// ── fetchable cpp tarball. GNU tar (CI/container) gets deterministic flags;
//    bsdtar (mac dev) falls back to a plain archive. The lockfile's per-file
//    content hashes are the authoritative pin — the tarball is just transport. ──
const tarball = `bundle-spec-cpp-${VERSION}.tar.gz`
let isGnuTar = false
try {
  isGnuTar = /GNU tar/.test(execFileSync('tar', ['--version'], { encoding: 'utf8' }))
} catch {
  /* --version unsupported → assume bsdtar */
}
const tarArgs = isGnuTar
  ? ['--sort=name', '--mtime=1970-01-01 00:00:00Z', '--owner=0', '--group=0', '--numeric-owner',
     '-czf', join(DIST, tarball), '-C', join(DIST, 'cpp'), '.']
  : ['-czf', join(DIST, tarball), '-C', join(DIST, 'cpp'), '.']
execFileSync('tar', tarArgs, { stdio: 'inherit' })

console.log(`  cpp     → dist/${tarball}  (+ dist/cpp/generated/cpp/, ${cppFiles.length + 1} headers)`)
console.log(`  python  → dist/python/  (installable speckle-bundle-spec==${VERSION})`)
console.log(`  query   → (lock only) conformance/query/, ${Object.keys(lock.targets.queryConformance.files).length} files`)
console.log(`  lock    → dist/bundle-spec.lock.json`)
console.log('done.')
