// Codegen's view of the spec: the repo's spec/bundle-spec.sql, through the same query
// code the published validator uses (packages/conformance/lib/spec.mjs) so the two can
// never disagree on how the spec is read.
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { createSpec } from '../../packages/conformance/lib/spec.mjs'

const here = dirname(fileURLToPath(import.meta.url))
export const REPO = join(here, '..', '..')
export const SPEC = join(REPO, 'spec', 'bundle-spec.sql')

/** Where codegen writes each language's output: inside the package that ships it. */
export const OUT = {
  ts: join(REPO, 'packages', 'ts', 'src'),
  sql: join(REPO, 'packages', 'ts', 'spec'),
  cpp: join(REPO, 'packages', 'cpp', 'include'),
  cs: join(REPO, 'packages', 'csharp'),
  py: join(REPO, 'packages', 'python', 'speckle_bundle_spec')
}

export const { query, relTypes, nodeKinds, bundleFiles, tableColumns, schemaVersion } =
  createSpec(SPEC)
export { SEMVER_RE } from '../../packages/conformance/lib/spec.mjs'

export const GENERATED_HEADER = (lang) => {
  // Per-language line-comment prefix: SQL `--`, Python `#`, everything else `//`.
  const c = lang === 'sql' ? '--' : lang === 'py' ? '#' : '//'
  return (
    // C#: the <auto-generated/> marker makes Roslyn analyzers (CAxxxx, naming, etc.)
    // skip the file — generated code is never hand-fixed, so its style isn't linted.
    (lang === 'cs' ? '// <auto-generated/>\n' : '') +
    `${c} GENERATED FROM spec/bundle-spec.sql — DO NOT EDIT.\n` +
    `${c} Run \`npm run generate\` (or node codegen/generate-all.mjs) to refresh.\n` +
    // auto-generated files need an explicit nullable context for the `string?` annotations (CS8669).
    (lang === 'cs' ? '#nullable enable\n' : '')
  )
}
